[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ip-scan"
version = "0.0.1"
authors = [
    { name = "Noah Young", email = "noah227@foxmail.com" },
]
description = "Scan if ip is available within specified range"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/noah227/ipscan"
"Bug Tracker" = "https://github.com/noah227/ipscan/issues"